---
- hosts: locans
# ansible
#virt_local
#  gather_facts: no

  roles:
#    - common/install
#    - common/sshkey
#    - common/php-fpm
#    - common/nodejs
#    - common/npm
    - common/composer
#    - common/Gitclone


