---
- hosts: ansible
#virt_local
#locans
# homeans
#  gather_facts: no

  roles:
#    - common/install
#    - common/sshkey
#    - common/nginx
#    - common/php-fpm
#    - common/nodejs
#    - common/npm
#    - common/composer
#    - common/memcached
#    - common/mongodb
#    - common/rabbitmq
#    - common/redis
#    - common/Gitclone
    - common/project_setup



