---
- hosts: mongo
  gather_facts: no

  tasks:
  - name: Upgrade and install required programs
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - htop
      - git-all
      - python-devel
    become: yes

  - name: Clone repository
    git:
      repo: git@github.com:SegaSan2/ansible-test.git
      dest: ~/1
      version: {{ git_branch }}
      user: git
      key_file: "{{ ssh_key }}"
      accept_hostkey: yes
      force: yes
      recursive: no

