---
- hosts: localhost
  vars:
    ip: 0.0.0.0, 192.168.2.1, 127.0.0.1

  tasks:
  - name: ted
#    debug: msg={{ ip.split(',') | map('replace', '0.0.0.0', '127.0.0.1', '192.168.1.3') | list }}
    debug: msg={{ ip.split(',') | map('replace', '127.0.0.1', '192.168.1.3') | list }}
