---
- name: Plug MongoDB repository
  template:
    src: ../templates/mongodb-org.repo.j2
    dest: /etc/yum.repos.d/mongodb-org.repo
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Plug MongoDB repository
  template:
    src: ../templates/mongodb-org_ams.repo.j2
    dest: /etc/yum.repos.d/mongodb-org.repo
  become: yes
  when: ansible_distribution == 'Amazon'

- name: Install Centos repo
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
#    - centos-release-scl
  become: yes
  when: ansible_distribution == 'CentOS'

- name: Upgrade and install required programs
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: "epel"
  with_items:
    - htop
    - git-all
    - python-devel
    - rsync
    - acl
    - xorg-x11-server-Xvfb
    - mongodb-org-shell
    - libXrender
    - wget
    - nfs-utils
    - supervisor
    - htop
    - iptraf-ng
    - python{{ py_ver }}
    - python{{ py_ver }}-pip
    - yum-utils
  become: yes

- name: Install pip ans fish for CentOS
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: "epel"
  with_items:
    - python2-pip
    - fish
  become: yes
  when: ansible_distribution == 'CentOS'
