- name: Copy Parameters
  copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    remote_src: yes
  with_items:
    - { src: '/var/www/{{ git_branch }}/app/config/parameters.yml.dist', dest: '/var/www/{{ git_branch }}/app/config/parameters.yml'}
    - { src: '/var/www/{{ git_branch }}/app/config/clients/maxibooking.env.dist' , dest: '/var/www/{{ git_branch }}/app/config/clients/maxibooking.env'}
    - { src: '/var/www/{{ git_branch }}/app/config/database.env.dist' , dest: '/var/www/{{ git_branch }}/app/config/database.env'}
    - { src:  '/var/www/{{ git_branch }}/app/config/secrets.yml.dist', dest: '/var/www/{{ git_branch }}/app/config/secrets.yml' }
    - { src:  '/var/www/{{ git_branch }}/app/config/version.yml.dist', dest: '/var/www/{{ git_branch }}/app/config/version.yml' }

- name: Composer install
#  become: yes
#  become_user: nginx
  composer:
    command: install
    working_dir: '/var/www/{{ git_branch }}'
    optimize_autoloader: true
    global_command: false
    no_dev: false

- name: Bower Install
  bower:
    path: '/var/www/{{ git_branch }}'

- name: Load Fixtures
  shell: 'php console {{item}}'
  args:
    chdir: '/var/www/{{git_branch}}/bin'
  with_items:
    - 'assets:install --symlink'
    - 'fos:js-routing:dump'
    - 'bazinga:js-translation:dump'
    - 'assetic:dump'
    - 'doctrine:mongodb:fixtures:load --no-interaction'
  when: load_fixtures
