- name: Copy Parameters
  copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'

    remote_src: yes
  with_items:
    - { src: '/var/www/{{ server_hostname }}/app/config/parameters.yml.dist', dest: '/var/www/{{ server_hostname }}/app/config/parameters.yml'}
    - { src: '/var/www/{{ server_hostname }}/app/config/clients/maxibooking.env.dist' , dest: '/var/www/{{ server_hostname }}/app/config/clients/maxibooking.env'}
    - { src: '/var/www/{{ server_hostname }}/app/config/database.env.dist' , dest: '/var/www/{{ server_hostname }}/app/config/database.env'}
    - { src:  '/var/www/{{ server_hostname }}/app/config/secrets.yml.dist', dest: '/var/www/{{ server_hostname }}/app/config/secrets.yml' }
    - { src:  '/var/www/{{ server_hostname }}/app/config/version.yml.dist', dest: '/var/www/{{ server_hostname }}/app/config/version.yml' }
#  become: yes

- name: Composer install
  composer:
    command: install
    working_dir: '/var/www/{{ server_hostname }}'
    optimize_autoloader: true
    global_command: false
    no_dev: false

- name: Bower Install
  bower:
    path: '/var/www/{{ server_hostname }}'

- name: Load Fixtures
  shell: 'php console {{item}}'
  args:
    chdir: '/var/www/{{server_hostname}}/bin'
  with_items:
    - 'assets:install --symlink'
    - 'fos:js-routing:dump --env=prod'
    - 'bazinga:js-translation:dump'
    - 'assetic:dump --env=prod'
    - 'doctrine:mongodb:fixtures:load --no-interaction'
  when: load_fixtures

- name: Change parameters.yml
  template:
    src: ../templates/parameters_yml.j2
    dest: /var/www/{{ server_hostname }}/app/config/parameters.yml
    owner: nginx
    group: nginx
    mode: 0664
    backup: yes
  become: yes

- name: Replace secrets.yml
  template:
    src: ../templates/secrets_yml.j2
    dest: /var/www/{{ server_hostname }}/app/config/secrets.yml
    owner: nginx
    group: nginx
    mode: 0664
    backup: yes
  become: yes

- name: Cache Clear
  shell: 'php console {{item}}'
  args:
    chdir: '/var/www/{{server_hostname}}/bin'
  with_items:
    - 'cache:clear --no-warmup --env=prod'

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
