---
  - name: Clone repository
    git:
      repo: git@bitbucket.org:MaxiBookingTeam/maxibooking-hotel.git
#      git@github.com:SegaSan2/ansible-test.git
      dest: /var/www/{{ git_branch }}
      version: "{{ git_branch }}"
#      user: git
      key_file: "{{ ssh_key }}"
      accept_hostkey: yes
      force: yes
#      recursive: no
#    become: yes
