---
# Install Nginx on Amazon server

# Upgrade before install
#- name: Upgrade all packages
#  yum:
#    name: '*'
#    state: latest
#  become: yes

- name: Install nginx
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - git
    - htop
  become: yes

- name: Start and enable nginx
#  become: yes
  service:
    name: nginx
    state: started
    enabled: yes

- name: Replace nginx.conf
  template:
    src: ../templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
#  become: yes
  notify:
    - restart nginx

- name: Create folder for sites file
  file:
    path: /etc/nginx/{{ item }}
    state: directory
  with_items:
    - sites-avaible
    - sites-enabled
  become: yes

- name: Add nginx rules /var/log/nginx folder
  file:
    path: /var/log/nginx/
    owner: nginx
    group: nginx
    mode: 0777
  become: yes

- name: Set attributes of nginx log files
  file:
    path: /var/log/nginx/{{ item }}
    owner: nginx
    group: nginx
    mode: 0664
  with_items:
    - error.log
    - access.log
  become: yes

- name: Update nginx conf for PHP
  template:
    src: ../templates/default-site.conf.j2
    dest: /etc/nginx/sites-avaible/{{ git_branch }}.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - restart nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-avaible/{{ git_branch }}.conf
    dest: /etc/nginx/sites-enabled/{{ git_branch }}.conf
    owner: root
    group: root
    state: link
  become: yes
  notify:
    - restart nginx



