---
  - name: Clone repository
    git:
      repo: git@bitbucket.org:MaxiBookingTeam/maxibooking-hotel.git
#      git@github.com:SegaSan2/ansible-test.git
      dest: /var/www/{{ page_for_nginx }}
      version: "{{ new_git_branch }}"
#      user: git
      key_file: "{{ ssh_key }}"
      accept_hostkey: yes
      force: yes
#      recursive: no
    become: yes

  - name: Set permission to deploy folder
    file:
      path: /var/www/{{ page_for_nginx }}
      state: directory
      owner: nginx
      group: nginx
#      mode: 0775
      recurse: yes
    become: yes

  - name: Ensure directories are 0775
    command: find /var/www/{{ page_for_nginx }}/ -type d -exec chmod 0777 {} \;
    become: yes

  - name: Ensure files are 0664
    command: find /var/www/{{ page_for_nginx }}/ -type f -exec chmod 0664 {} \;
    become: yes

#  - name: Find file for change permission
#    find:
#      path: /var/www/{{ git_branch }}/
#      file_type: file
#      recurse: yes
#    register: find_result
#
#  - name: Set permission to deploy file
#    file:
#      path: "{{ item.path }}"
#      mode: u=rw,g=rw,o=r
#    become: yes
#    with_items:
#      "{{ find_result.files }}"

